config/routes.rb
Rails.application.routes.draw do

  devise_for :users


  root 'homes#top'
  get 'homes/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users,only: [:show,:edit,:update,:index] do
  	resources :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  #favorite消すのに
  get 'team_fav_delete' => 'favorites#destroy'
  #post 'teams/comments_create' => 'team_comments#create'
  resources :teams, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :team_comments, only: [:create, :destroy] do
    	resources :favorites,except: [:create, :destroy] do
    	    collection do
    	    	post :create_comment_fav
    	    	delete :destroy_comment_fav
    	    end
        end
    end
    resources :favorites, only: [:create, :destroy]

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable  
  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 400}
  attachment :profile_image, destroy: false
  has_many :teams
  has_many :team_comments
  has_many :favorites
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    #@teams = @user.teams
    @teams = @user.teams.page(params[:page]).per(10).order(id: "desc") 
    @team_new = Team.new
  end

  def index
    #@users = User.all
    @users = User.page(params[:page]).per(10).order(id: "desc") 
    @team_new = Team.new
    #@user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end
  def follows

  end

  def followers
    
  end

  private
    def user_params
       params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def screen_user
      unless params[:id].to_i == current_user.id
        redirect_to user_path
      end
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
  <div class="row">
    <div class='col-xs-4'>
      image
    </div>
    <div class='col-xs-4'>
      user_name
    </div>
    <div class='col-xs-4'>
    </div>
  </div>
  <div style="border-bottom: 5px solid blue;"></div>
  <% users.each do |user| %>
    <div class="row" style="margin-bottom:30px;">
      <div style="border-top: 2px solid blue;"></div>
      <div class="col-xs-4">
        <%= attachment_image_tag user, :profile_image, size:"60x60", fallback: "icon.jpg" %>
      </div>
      <div class="col-xs-4">
        <%= user.name %>
      </div>
      <div class="col-xs-4">
        <%= link_to 'Show', user, class: "user_#{user.id}" %>
      </div>
    </div>
  <% end %>
  <%= paginate users %>

app/views/users/_profile.html.erb
<table class='table'>
    <tr>
      <th>image</th>
      <th>user_name</th>
      <th>introduction</th>
      <th colspan="3"></th>
    </tr>
  <tbody>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size:"60x60", fallback: "icon.jpg" %></td>
        <td><%= user.name %></td>
        <td><%#=safe_join(user.introduction.split("\n"),tag(:br))%></td>
      </tr>
  </tbody>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>




   

app/views/users/_show.html.erb
  <div class="row">
    <div class='col-xs-3'>
      image
    </div>
    <div class='col-xs-3'>
      team_name
    </div>
    <div class='col-xs-3'>
      description
    </div>
    <div class='col-xs-3'>
      favorites
    </div>
  </div>
  <div style="border-bottom: 5px solid red;"></div>
  <% teams.each do |team| %>
   <div class="row" style="margin-bottom:30px;">
    <div class='col-xs-3'>
      <%= attachment_image_tag team, :image, :fill, 100, 100 %>
    </div>
    <div class='col-xs-3'>
      <%= link_to team.name,team, class: "team_#{team.id}" %>
    </div>
    <div class='col-xs-3'>
      <%= team.body %>
    </div>
    <div class='col-xs-3'>
      <% if team.favorited_by?(current_user) %>
        <% favorite = team.favorites.find_by(user_id: current_user.id) %>
        <%#= link_to team_favorite_path(team, team.favorite_id, redirect_id: 0), method: :delete do %>
        <%= link_to team_fav_delete_path(favorite_id: favorite.id) do %>
        <span class="glyphicon glyphicon-heart"><%= team.favorites.count%></span>
        <% end %>
      <% else %>
        <%= link_to team_favorites_path(team, redirect_id: 0), method: :post do %>
          <span class="glyphicon glyphicon-heart-empty"><%= team.favorites.count %></span>
        <% end %>
      <% end %>
    </div>  
   </div>
  <% end %>
  <%= paginate teams %>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= render 'layouts/error_messages', model: @user %>

<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :image %>
    <%= attachment_image_tag @user, :profile_image, size:"60x60", fallback: "icon.jpg" %>
    <%= f.attachment_field :profile_image, class: "user_image" %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "name" %>
  </div>
  <div class="field">
    <%= f.label :introduction %><br>
    <%= f.text_area :introduction, class: "introduction" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container-fluid">
  <div class='row'>
    <div class='col-xs-11'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='row'> 
 <div class='hidden-sm col-md-3'>
    <h2>User info</h2>
      <%= render 'users/profile', user: @user %>
    <h2>New Team</h2>
      <%= render 'teams/form', team_new: @team_new %>
      <%#= render partial: 'teams/form', locals: {team_new: @team_new, team: @team} %>
 </div>
 <div class='col-sm-12 col-md-9'>
    <h2>My Teams</h2>
      <%= render 'users/show', teams: @teams %>
 </div>
</div>