config/routes.rb
Rails.application.routes.draw do

  devise_for :users


  root 'homes#top'
  get 'homes/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users,only: [:show,:edit,:update,:index] do
  	resources :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  #favorite消すのに
  get 'team_fav_delete' => 'favorites#destroy'
  #post 'teams/comments_create' => 'team_comments#create'
  resources :teams, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :team_comments, only: [:create, :destroy] do
    	resources :favorites,except: [:create, :destroy] do
    	    collection do
    	    	post :create_comment_fav
    	    	delete :destroy_comment_fav
    	    end
        end
    end
    resources :favorites, only: [:create, :destroy]

  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      	<li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container">
		<h4><%= link_to "-サイトについて-",homes_about_path,:style=>"color:green;" %></h4>
		<h4>ウィニングイレブンユーザーの為の　　　　©CopyRight　　squad　 All Rights Reserved.</h4>
	</div>
</div>

app/views/layouts/_logout_header.html.erb
<div class="header">
	<div class="container">
		<div class="row header_content">
			<div class="col-xs-2">
				<%= link_to root_path do %>
				<%= image_tag 'squad.jpg', :size =>'200x100' %>
				<% end %>
			</div>
			<div class="col-xs-6"></div>
			<div class="col-xs-4">
				<table class="table header_table">
					<tr>
						<td></td>

						<td></td>
						<td><%= link_to "about", homes_about_path, class: "btn btn-default" %></td>
						<td><%= link_to "ログイン", new_user_session_path, class: "btn btn-default" %></td>
						<td><%= link_to "サインアップ", new_user_registration_path, class: "btn btn-default" %></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_user_header.html.erb
<div class="header">
	<div class="container">
		<div class="row header_content">
			<div class="col-xs-2">
				<%= link_to root_path do %>
				<%= image_tag 'squad.jpg', :size =>'200x100' %>
				<% end %>
			</div>
		<div class="col-xs-2"></div>
			<div class="col-xs-8">
				<table class="table header_table">
					<tr>
						<td>ようこそ、<%= current_user.name %>さん！</td>
						<td><%= link_to edit_user_path(current_user) do %>
  							<span class="glyphicon glyphicon-user" aria-hidden="true"></span></td>
						<% end %>
						<td><%= link_to new_team_path do %>
							<span class="btn btn-primary">＋</span></td>
						<% end %>
						<td><%= link_to "マイページ", user_path(current_user.id), class: "btn btn-default" %></td>
						<td><%= link_to "ユーザー一覧", users_path, class: "btn btn-default" %></td>
						<td><%= link_to "スカッド", teams_path, class: "btn btn-default" %></td>
						<td><%= link_to "ログアウト", destroy_user_session_path,method: :delete, class: "btn btn-default" %></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Squad</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/user_header' %>
    <% else %>
      <%= render 'layouts/logout_header' %>
    <% end %>
    <div class="container-fluid">
      <h3 class="notice"><%= notice %></h3>
      <%= yield %>
    </div>
  </body>
  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</html>